name: NewsAppBuild
on:
  pull_request :
    branches : [ master ]
    push :
      branches : [ master ]

jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name : Setup Java
        uses: actions/setup-java@v3
      - name : Build with Gradle
        run : ./gradlew build
      - name : Upload a build artifact
        uses: actions/upload-artifact@v3
        with:
          name: NewsApp.apk
          path: app/build/outputs/apk/app-debug.apk



